repos:
-   repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.4.4
    hooks:
      # Roda o linter
      - id: ruff
        args: [ --fix ]
      # Roda o formatador
      - id: ruff-format
